# Default values for glooctl-installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# only set this for testing, GCP Marketplace disallows the creation of rbac resources during installation (user should prepare a service account in advance)
rbac: false
debug: false

# for debugging, this gates all the resources released by the marketplace
# it is on by default
marketplaceResources: true

enterpriseLicense: "set-by-marketplace"

glooctlInstaller:
  serviceAccount: glooctl-installer
  image:
    repository: gcr.io/solo-io-public/gloo/installer
    tag: "1.1c"
    pullPolicy: IfNotPresent

