{{- if .Values.rbac }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: glooctl-installer
    namespace: {{ .Release.Namespace }}
    labels:
        app: gloo
        gloo: rbac
rules:
  # for now, give access to everything
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["gloo.solo.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["gateway.solo.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io/v1beta1"]
  resources: ["*"]
  verbs: ["*"]
# - apiGroups: [""]
#   resources: ["pods", "services", "secrets", "endpoints", "configmaps", "namespaces"]
#   verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: glooctl-installer
    namespace: {{ .Release.Namespace }}
    labels:
        app: gloo
        gloo: rbac
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io/v1beta1"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooctl-installer
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: glooctl-installer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: glooctl-installer
  apiGroup: rbac.authorization.k8s.io
---
# TODO: remove cluster roles. for now, give access to everything
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooctl-installer
  labels:
    app: gloo
    gloo: rbac
subjects:
- kind: ServiceAccount
  name: {{ .Values.glooctlInstaller.serviceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: glooctl-installer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: {{ .Values.glooctlInstaller.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end }}
